name:                whilelang
version:             0.1.0.0
github:              "githubuser/whilelang"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/whilelang#readme>

dependencies:
- base >= 4.7 && < 5
- yapb >= 0.2.6
- containers
- z3 >= 408.2

library:
  source-dirs: src

executables:
  whilelang-exe:
    main:                Main.hs
    source-dirs:         
    - app
    - app/ast
    - app/interp
    - app/typecheck
    - app/dataflow
    - app/symexec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whilelang

tests:
  whilelang-test:
    main:        Spec.hs
    source-dirs: 
    - test
    - app
    - app/ast
    - app/interp
    - app/typecheck
    - app/dataflow
    - app/symexec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whilelang

